version: "3.8"
services: 
  pulsar:
    container_name: pulsar
    hostname: pulsar
    image: apachepulsar/pulsar:2.10.4
    ports:
      - "6650:6650"
      - "8080:8080"
    command: >
      /bin/bash -c "bin/pulsar standalone"
    #volumes:
      #- ./pulsardata/:/pulsar/data

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"

  producer:
    image: 127.0.0.1:5000/producer
    build:
      context: ./producer
      network: host
    #network_mode: host
    depends_on:
      - pulsar
    restart: unless-stopped

  consumer:
    image: 127.0.0.1:5000/consumer
    build:
      context: ./consumer
      network: host
    #network_mode: host
    depends_on:
      - pulsar
    restart: unless-stopped
