apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  clusterIP: 10.43.0.11
  type: NodePort
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      nodePort: 30007
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}
