apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: pulsar
  name: pulsar
spec:
  clusterIP: 10.43.0.12
  type: ClusterIP
  ports:
    - name: "6650"
      port: 6650
      targetPort: 6650
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: pulsar
status:
  loadBalancer: {}
